### ISSUE TITLE
Thanks for your invitation on GitHub.

### ISSUE THREAD

**Issue by airingursb** [GZHU-Dress/GZHU-Wikiii#4]
Hey axionl,

I am Airing. Thanks for your invitation on GitHub.

However, may I ask you some questions?
Could you please introduce yourself firstly and tell me what the organization works on?

At last, thank you for the invitation again.

Sincerely,
Airing.

PS. 因为我之前发你邮件没有回，于是就issue了

**Comment by axionl** [comment]
On Friday, September 15, 2017 10:46 UTC, Airing <notifications@github.com> wrote: 
 
> Hey axionl,
> 
> I am Airing. Thanks for your invitation on GitHub.
> 
> However, may I ask you some questions?
> Could you please introduce yourself firstly and tell me what the organization works on?
> 
> At last, thank you for the invitation again.
> 
> Sincerely,
> Airing.
> 
> PS. 因为我之前发你邮件没有回，于是就issue了
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/GZHU-Dress/GZHU-Wikiii/issues/4 
 
 
 
您好，抱歉最近忘了看邮箱。我是目前GZHU在校的一名学生，这个组织主要的建立目的是希望校内技术力量之间能够有更多的技术交流，以及建立一个更加开放自由的环境。因为之前看到您似乎在做广州大学相关的项目，所以冒昧便发出了邀请，还望海涵。组织的项目的内容类型不限，只要是相关的愿意分享的就行。在线群组：https://t.me/joinchat/DtA8zg3FXVT05WEU4m7o8Q
